#!/bin/sh /etc/rc.common
# Init Script for firewall-auth

START=90

start() {
        start-stop-daemon \
                -S \
                -q \
                -b \
                -m \
                -p /var/run/firewall-auth.pid \
                -x /root/firewall-auth.sh
}
stop() {
        start-stop-daemon \
                -K \
                -q \
                -p /var/run/firewall-auth.pid
}
